baseURL = 'https://465123.xyz/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
title = '逍遥云梦客'
theme = 'reimu'
themesDir = 'themes'

[languages.zh-CN]
  languageName = '简体中文'
  hasCJKLanguage = true

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup.goldmark.renderer]
unsafe = true

[outputs]
  home = ["HTML", "RSS"]